In [1]:
import numpy as np

from synthesizing import Synthesis

In [2]:
refrain =  np.array([
        [220, 200, 100, 200, 250],
        [  0, 300, 150, 400, 500],
        [  0, 600, 250, 600, 600]
    ])

durations = [0.5, 0.5, 0.5, 0.5]
sample_rate = 22050

In [10]:
timbre = ((1, 0.8), (2, 0.5), (4, 0.25), (8, 0.1))
timbre[0][1]

0.8

In [4]:
S = Synthesis(
    refrain,
    durations,
    sample_rate,
    timbre=timbre
)

0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2


In [5]:
for factor,amplitude in timbre:
    print(factor, amplitude)

1 0.8
2 0.5
4 0.25
8 0.1


In [6]:
for i,(factor,amplitude) in enumerate(timbre):
    if i > 0 :
        print(refrain*factor)
        refrain = np.concatenate((refrain, refrain*factor))

[[ 440  400  200  400  500]
 [   0  600  300  800 1000]
 [   0 1200  500 1200 1200]]
[[ 880  800  400  800 1000]
 [   0 1200  600 1600 2000]
 [   0 2400 1000 2400 2400]
 [1760 1600  800 1600 2000]
 [   0 2400 1200 3200 4000]
 [   0 4800 2000 4800 4800]]
[[ 1760  1600   800  1600  2000]
 [    0  2400  1200  3200  4000]
 [    0  4800  2000  4800  4800]
 [ 3520  3200  1600  3200  4000]
 [    0  4800  2400  6400  8000]
 [    0  9600  4000  9600  9600]
 [ 7040  6400  3200  6400  8000]
 [    0  9600  4800 12800 16000]
 [    0 19200  8000 19200 19200]
 [14080 12800  6400 12800 16000]
 [    0 19200  9600 25600 32000]
 [    0 38400 16000 38400 38400]]


In [7]:
refrain

array([[  220,   200,   100,   200,   250],
       [    0,   300,   150,   400,   500],
       [    0,   600,   250,   600,   600],
       [  440,   400,   200,   400,   500],
       [    0,   600,   300,   800,  1000],
       [    0,  1200,   500,  1200,  1200],
       [  880,   800,   400,   800,  1000],
       [    0,  1200,   600,  1600,  2000],
       [    0,  2400,  1000,  2400,  2400],
       [ 1760,  1600,   800,  1600,  2000],
       [    0,  2400,  1200,  3200,  4000],
       [    0,  4800,  2000,  4800,  4800],
       [ 1760,  1600,   800,  1600,  2000],
       [    0,  2400,  1200,  3200,  4000],
       [    0,  4800,  2000,  4800,  4800],
       [ 3520,  3200,  1600,  3200,  4000],
       [    0,  4800,  2400,  6400,  8000],
       [    0,  9600,  4000,  9600,  9600],
       [ 7040,  6400,  3200,  6400,  8000],
       [    0,  9600,  4800, 12800, 16000],
       [    0, 19200,  8000, 19200, 19200],
       [14080, 12800,  6400, 12800, 16000],
       [    0, 19200,  9600, 256